### ISSUE TITLE
Section headings in 37-dag_tshig_gsar_bsgrigs-Tib

### ISSUE THREAD

**Issue by nbuwe** [christiansteinert/tibetan-dictionary#13]
"dag yig gsar bsgrigs" has extra section headings for initial consonant clusters, like "lta", "sta", "blta", "bsta" ...

`37-dag_tshig_gsar_bsgrigs-Tib` has empty entries for such sections that leak into the search output.  Some of them seems to have been cleaned up, e.g. there's no bogus entry for "kla", but some remain, e.g. "sta".

```
$ grep '|/$' 37-dag_tshig_gsar_bsgrigs-Tib  | wc -l
24
```

Cf. https://archive.org/details/bdrc-W8LS30619/

**Comment by christiansteinert** [comment]
Thank you for this.  I have commented out the respective entries. The online dictionary is fixed as of now. The Android app will receive the fix with the next regular release.

**Comment by nbuwe** [comment]
I think it's better to g/c them.  They are just a few random leftovers, the original paper dictionary has these section headings for *all* consonant clusters.

**Comment by christiansteinert** [comment]
Why not. I have removed them completely.
