### ISSUE TITLE
dung-dkar tshig-mdzod chen-mo, typo in listing for རྟགས་བཅུ་

### ISSUE THREAD

**Issue by jfhartzell** [christiansteinert/tibetan-dictionary#16]
(རྟགས་བཅུ Steinert: dung-dkar tshig-mdzod chen-mo, the Great White Conch Dictionary, 
See the third item, where ཆུ་རླུང་is mistakenly written as ཆུ་ང་
རྣལ་འབྱོར་པ་དམིགས་པ་ལ་སེམས་ཟིན་པས།་ 
༡་ས་རླུང་ཟིན་པས་དུབ་སྔོན་བུན་ནོ།་
༢་མེ་རླུང་ཟིན་པས་སྲིན་བུ་མེ་ཁྱེར་ལྟ་བུའོ།
།༣་ཆུ་(རླུ)ང་ཟིན་པས་སྨིག་རྒྱུ་ལྟ་བུའོ།

**Comment by christiansteinert** [comment]
Will be fixed soon. Many thanks
