### ISSUE TITLE
Repetitive definition in མངོན་ཤེས་ལྔ་

### ISSUE THREAD

**Issue by jfhartzell** [christiansteinert/tibetan-dictionary#20]
Under མངོན་ཤེས་ལྔ་, under Rangjung Yeshe, the first part of the definition is repeated:

five superknowledges
five superknowledges [1 ལྷའི་མིག་ – ལྷའི་རྣ་བ་ – གཞན་གྱི་སེམས་ཤེས་པ་-) འཆི་འཕོ་དང་སྐྱེ་བ་དྲན་པ་ -) རྫུ་འཕྲུལ་གྱི་མངོན་པར་ཤེས་པ་ chn [R] rdzu 'phrul gyi mngon shes dang, lha'i mig gi mngon shes, lha'i rna ba'i mngon shes, sngon gnas rjes dran gyi mngon shes, gzhan sems shes pa'i mngon shes bcas lnga

five superknowledges [1 ལྷའི་མིག་ – ལྷའི་རྣ་བ་ – གཞན་གྱི་སེམས་ཤེས་པ་-}-) འཆི་འཕོ་དང་སྐྱེ་བ་དྲན་པ་ -}-) རྫུ་འཕྲུལ་གྱི་མངོན་པར་ཤེས་པ་ chn [R] rdzu 'phrul gyi mngon shes dang, lha'i mig gi mngon shes, lha'i rna ba'i mngon shes, sngon gnas rjes dran gyi mngon shes, gzhan sems shes pa'i mngon shes bcas lnga
Five superknowledges. The capacities for performing miracles, divine sight, divine hearing, recollection of former lives, and cognition of the minds of others
--

**Comment by christiansteinert** [comment]
Many thanks! 

I will remove the part that is fully duplicated and the change will be active soon. There is still some semi-duplication in the first half of the definition but I have left this as is for now since this is more of an editorial issue.
