### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by jfhartzell** [christiansteinert/tibetan-dictionary#21]
When accessing 
འདོན་པ་
using Ecosia, I get this error message:

parsererror
SyntaxError: JSON Parse error:
"\uof7/(" is not a valid unicode escape

error only occurs with འདོན་པ་, not with compound forms

**Comment by christiansteinert** [comment]
There were some invalid unicode escape sequences in some entries of Negi. The  affected entries have now been fixed. 
With this 'don pa works as expected.
