### ISSUE TITLE
དངངས་སྐྲག entry not parsed correctly

### ISSUE THREAD

**Issue by drupchen** [christiansteinert/tibetan-dictionary#28]
The below entry should be:

entry: དངངས་སྐྲག་
definition: འཇིགས་སྐྲག དངངས་སྐྲག་སྐྱེས་པ། དངངས་སྐྲག་ཚབ་ཚུབ། དངངས་སྐྲག་མ་སྐུལ།

![image](https://user-images.githubusercontent.com/13376036/233416881-baf441af-1f7b-48a4-8ffb-623a5b351cf5.png)

**Comment by christiansteinert** [comment]
Thanks a lot for the remark! Will be fixed soon.
