### ISSUE TITLE
"bas" input is transliterated "bsa"

### ISSUE THREAD

**Issue by tempapy** [christiansteinert/tibetan-dictionary#30]
Hello,

I noticed that when you type "bas", either in Tibetan script or transliteration, it is converted to "bsa" as the search input (in the URI), so any word containing "bas" yields no results (unless you edit the URI manually). 

Thank you for your wonderful website!

**Comment by tempapy** [comment]
It's fixed, or maybe I was dreaming.

**Comment by christiansteinert** [comment]
I don't think that you were dreaming. I did make a change which should prevent this problem for the syllable your mentioned. 

If you encounter a similar problem with other syllables, please continue to create bug reports so that I can fix any syllables that are broken...

Many thanks!
Christian
