### ISSUE TITLE
Negi existing hyperlinked grammatical abbreviations:

### ISSUE THREAD

**Issue by jfhartzell** [christiansteinert/tibetan-dictionary#31]
vi.: viśeṣaṇam
This is hyperlinked in Negi's 2nd definition of "ལོངས་སྤྱོད་རྫོགས་པ་"

in Negi's "ཅི་རིགས་པ་", the definition "vi. yathārhā," lacks the hyperlink for "vi"

**Comment by jfhartzell** [comment]
nā.: nāma (vyattivācakasaṃjñā)
in Negi's last definition of "རྣོན་པོ"

**Comment by jfhartzell** [comment]
kri.: kriyā
in Negi's first definition of "རྣམ་པར་རྟོག་པ་"

**Comment by christiansteinert** [comment]
Thanks for contributing these abbreviations! I have added them to the application.

**Comment by jfhartzell** [comment]
Happy to contribute and will post more if I find themEnviado desde mi iPhoneEl 6 ago 2023, a las 22:48, christiansteinert ***@***.***> escribió:﻿
Thanks for contributing these abbreviations! I have added them to the application.

**Comment by jfhartzell** [comment]
Negi སྟེར་བྱེད་ has kri. without the kriyā hyperlink

**Comment by jfhartzell** [comment]
"bhūta."/ should be hyperlinked to "bhūtakālaḥ"
