### ISSUE TITLE
UTF16 characters in the TIbetan abbreviations dictionary

### ISSUE THREAD

**Issue by TempaYeshe** [christiansteinert/tibetan-dictionary#34]
Hi,

In the TIbetan abbreviations dictionary, there are two entries (with their respective reverse entries), `mi 'phra[􀴙]d+nyi` and `ba[󲀱]da`, which include utf16 characters in brackets. The two codepoints used are 100d19 and f2031, which are private use codepoints. 

These entries have an encoding problem because of the Dzongkha abbreviations pdf: it encodes as `མི་འཕྲོདྙི་.` as `མི་འཕྲ�དྙི།` and `བཀྡོད།` as `བ󲀱ད།`. 

Thus, in the `51-LaineAbbreviations` file, `mi 'phra[􀴙]d+nyi` has to be replaced by `mi 'phrod+nyi` and `ba[󲀱]da` by `bak+dod` (maybe `bk+dod`?). 

I also communicated the issue to the RTKS website (Edit: fixed there). 

Thank you

**Comment by christiansteinert** [comment]
Sincere apologies for not responding earlier to your report. I was very busy at the end of last year and then started to have severe problems with my back early this year which caused a lot of  things to fall to the side.

I have fixed the input files for the dictionary now and with the next update  of the website the dictionary entries should also get fixed. 

I am very grateful for your very detailed report. If you see other, similaer problems, I always appreciate a report, even if it may take me a while to fix it.
