### ISSUE TITLE
Negi: missing hyperlinks, grammatical abbreviations

### ISSUE THREAD

**Issue by jfhartzell** [christiansteinert/tibetan-dictionary#35]
a) Negi སྟེར་བྱེད་ has kri. without the kriyā hyperlink
b) "bhūta." should be hyperlinked to "bhūtakālaḥ" in all instances (i.e., past tense)
(it is hyperlinked in བསྟན་ (first line of definition), but not in every instance elsewhere)
"bhavi." should be hyperlinked to "bhaviṣyakālaḥ" in all instances (i.e., future tense)
"varta" should be linked to "vartamānakālaḥ" in all instances (i.e. present tense)
(see for example kri. (varta., bhavi.; bhūta.) under "འཁྱམ་པ་"
c) pā in ཀུན་གཞི་རྣམ་པར་ཤེས་པ་ is missing the "pāribhāṣikaśabdaḥ" hyperlink.

**Comment by christiansteinert** [comment]
Dear James, 

Thank you so much for the detailed and helpful bug report. Apologies for taking such a long time to respond. I had some health problems since early this year from which I am still gradually recovering. 

I have fixed the abbreviation handling for the Negi dictionary. All the cases that you mentioned should be fixed now and hopefully other situations as well.

Many thanks and please keep reporting if you find other problems.

Many thanks,
Christian

**Comment by jfhartzell** [comment]
Dear ChristianThanks for your kind note, and for the continued phenomenal help your dictionary system provides. I'll happily note anything I come across, though latetly I haven't seen anything.I noticed recently that Negi abbreviations all seem to be working, so I suspected you'd been working on it!I've also battled through some health issues this year, and that has also substantially impeded progress on several projects, though things are gradually picking up again, so I can empathize.Cheers,JamesJames Hartzell, PhD(2x), Exec.MBADonostia-San Sebastián, SpainOn 3 Nov 2024, at 17:26, christiansteinert ***@***.***> wrote:﻿
Dear James,
Thank you so much for the detailed and helpful bug report. Apologies for taking such a long time to respond. I had some health problems since early this year from which I am still gradually recovering.
I have fixed the abbreviation handling for the Negi dictionary. All the cases that you mentioned should be fixed now and hopefully other situations as well.
Many thanks and please keep reporting if you find other problems.
Many thanks,
Christian

**Comment by jfhartzell** [comment]
Hi Christian
I think I found another one: under སྔོན་ in Negi, there's an "avya." abbreviation under definition 2 that doesn't show a hyper link to a clarification in any of the browsers I have.

**Comment by jfhartzell** [comment]
Negi: another one, under "རྒྱས་པ་", 2nd bullet, "saṃ" has no hyperlink clarification

**Comment by jfhartzell** [comment]
same under Negi "དགུག་པ་", the "saṃ" abbreviation lacks the hyperlink clarification

**Comment by jfhartzell** [comment]
same under Negi "རི་", no hyperlink of "saṃ" abbreviation

**Comment by christiansteinert** [comment]
Dear James,

Thank you so much for reporting these. You are right. 

I checked the list of abbreviations and sadly I do not currently have the abbreviations for avya. and for saṃ.

What would these abbreviations refer to in your opinion? avyakta and saṃskṛta?

**Comment by jfhartzell** [comment]
Dear ChristianI was a bit stumped myself on these, so I asked Mistral.ai (a relatively new [with free version] french ai engine, if you don't already know about it) and this is the answer it gives:"avya.: This is an abbreviation for "avyaya," which means "indeclinable" or "particle." In Sanskrit grammar, avyayas are words that do not change their form regardless of their grammatical function. They include particles, adverbs, prepositions, and conjunctions. saṃ.: This is an abbreviation for "saṃyoga," which means "conjunction" or "combination." In Sanskrit grammar, saṃyoga refers to the joining or combination of sounds, words, or phrases. It is a fundamental concept in the study of Sanskrit phonetics and morphology."I'll check going forwards whether these are the correct explanations, but they sound reasonable to me. What do you think?Cheers,JamesJames Hartzell, PhD(2x), Exec.MBADonostia-San Sebastián, SpainOn 12 Nov 2024, at 22:58, christiansteinert ***@***.***> wrote:﻿
Dear James,
Thank you so much for reporting these. You are right.
I checked the list of abbreviations and sadly I do not currently have the abbreviations for avya. and for saṃ.
What would these abbreviations refer to in your opinion? avyakta and saṃskṛta?

**Comment by jfhartzell** [comment]
one of my sanskrit teachers confirms avya. would be avyayam, ie the indeclinablesstill working on sam.James Hartzell, PhD(2x), EMBADonostia-San Sebastián, SpainOn 12 Nov 2024, at 22:58, christiansteinert ***@***.***> wrote:﻿
Reopened #35.

**Comment by jfhartzell** [comment]
i checked སྔོན་ that has in Negi 'avya.' then bhūtapūrvam. In Sanskrit bhūtapūrvam is indeed an indeclinable meaning 'formerly'.

**Comment by jfhartzell** [comment]
The only possibility we can see for 'saṃ' is saṃjñā. We don't find any other Sanskrit grammatical term that matches both the abbreviation and the way Negi lists words preceded by 'saṃ'. Though 'saṃjñā' in the dictionaries is defined as a formal name (e.g. for a person), in Sanskrit grammar it appears to be used as the 'name'/technical term for a word element or word type, e.g. prātipadika-saṃjñā, i.e. the base form of a word before it is declined, dhātu-saṃjñā (verb roots), kṛt-saṃjñā (primary verbal suffixes) taddhita-saṃjñā (a type of suffix for making nouns), etc. The way Negi seems to have used it is as a marker for all the varieties of derivative words related to the verb root.

**Comment by jfhartzell** [comment]
this is the best I can come up with for now!

**Comment by christiansteinert** [comment]
Thank you for putting in the work into tracking these down! I have added these two abbreviations. Again, it can take a few days before you see it because of your local browser cache.

By the way: I also found scanned volumes 5 / 6 / 7 / 9 of Negi on archive.org: https://archive.org/search?query=J.+S.+Negi++
But sadly sadly, there are only the abbreviations for sources listed there, not the abbreviations for grammatical terms.

**Comment by jfhartzell** [comment]
You're most welcome. It was a fun adventure and I learned new things about Paninian grammatical terminology. I hope we got it correct for saṃjñā!  Are you on the Indology list serve group? You could ask there if anyone has the full set of grammatical abbreviations for the Negi dictionary volumes. There are several Indologists who also work in Tibetan, so someone might know.James Hartzell, PhD(2x), Exec.MBADonostia-San Sebastián, SpainOn 25 Nov 2024, at 22:56, christiansteinert ***@***.***> wrote:﻿
Thank you for putting in the work into tracking these down! I have added these two abbreviations. Again, it can take a few days before you see it because of your local browser cache.
By the way: I also found scanned volumes 5 / 6 / 7 / 9 of Negi on archive.org: https://archive.org/search?query=J.+S.+Negi++
But sadly sadly, there are only the abbreviations for sources listed there, not the abbreviations for grammatical terms.

**Comment by jfhartzell** [comment]
Under འགྱུར་ I see Negi (Tibetan-Sanskrit)
= འགྱུར་བ། འགྱུར་ ནས་ bhūtvā 
the འགྱུར་བ། is missing the hyperlink to the འགྱུར་བ། definition

**Comment by christiansteinert** [comment]
I have no connection to the Indology list serve. If you do, I would be grateful if you could ask around about the list of abbreviations. It really seems as if the books themselves do not list the abbreviations, unless the first volume is somehow different from the scanned ones that I found.

Regarding the entry for འགྱུར་: This is a general limitation of the current dictionary code - it only links a section of Tibetan text if that whole section is exactly matching a dictionary entry. Splitting up longer passages is more complicated so they are not linked even if they contain one ore more terms.

In the particular case the entry is a bit funny. The Negi data that I have is split up into "འགྱུར་བ། འགྱུར་" plus "ནས་". For ནས་ there is an exact dictionary entry so that one gets linked. For "འགྱུར་བ། འགྱུར་" there is no exact entry so it does not get linked. This splitting in this particular entry is a bit peculiar but there is not much point of changing just that. The underlying problem is that longer Tibetan passages are not currently split up so that the individual terms cannot be linked. Maybe at some point I will manage to add more processing in order to find contained terms in longer Tibetan passages.

**Comment by jfhartzell** [comment]
Hi Christian
I checked with an Indology colleague who's a pro with Sanskrit Tibetan stuff (prof emeritus now). He found in vol 10 of Negi that the abbreviation 'saṃ' is in fact for the word 'saṃjñā', so you can confidently update the hyperlink.  He says in volume 6 t just says 'sa' but he thinks that's a typo.

**Comment by christiansteinert** [comment]
Thanks for the very helpful confirmation. This is really great to know. I will also add sa. as an additional abbreviation for saṃjñā - I looked at the entries and saw that indeed for some of the entries only sa. is used as an abbreviation.

**Comment by jfhartzell** [comment]
Hi Christian
Found missing hyper links for the citations
sū.vyā.148ka/29 and sū.vyā.207kha/111 under definition #1 prabhedaḥ for རབ་ཏུ་དབྱེ་བ་

**Comment by jfhartzell** [comment]
Hi Christian
Found missing hyper links for the citations
sū.vyā.148ka/29 and sū.vyā.207kha/111 under definition #1 prabhedaḥ for རབ་ཏུ་དབྱེ་བ་

**Comment by jfhartzell** [comment]
Hi Christian

I have a possible suggestion for your setup, though I have no idea how much work it would involve.
Here's the example: today I looked up this phrase: ཡང་དག་པར་སྦྱོར་བས་ and the system shows no entries. Then I modify it slightly to ཡང་དག་པར་སྦྱོར་བ་ and the definitions come up. The first was within the sentence, the second the Tibetan-translation-of-Sanskrit word itself, saṃyujyate, saṃyogaḥ, etc.  
Might it be possible (without much strain) to modify your setup slightly so that it somehow would show the 'slightly' different words that more or less match a request?
I.e. if I ask for the definition of ཡང་དག་པར་སྦྱོར་བས་ or similar instances, i.e. the words as they appear within a grammatical structure of a sentence, your system would pull up and show the word itself ཡང་དག་པར་སྦྱོར་བ་ ?
Otherwise hope all is well. Here we're chugging along, integrating life now with adult children and their kids who've delightfully decided to move here to our small city from their fancier lives in California(!) because they prefer the lifestyle here.
Cheers
James

**Comment by christiansteinert** [comment]
Thank you for this suggestion. This is not a trivial thing but a good idea. I am considering to add some extended search option. What you describe is basically a similarity search (also called fuzzy search). It is not trivial to implement but I think it is worthwhile to consider. 

I have to see how I can add something like this in a way that can search the information quickly enough while not searching in an exact way. This will be the trickiest aspect. 

I will keep this in the back of th my mind and when time allows I will start experimenting. If the experiments are successful then this could become of a group of extended search options that I want to look into and experiment with.

Thanks for the suggestion!
