### ISSUE TITLE
Dump to bgl/ babylon files

### ISSUE THREAD

**Issue by vvasuki** [christiansteinert/tibetan-dictionary#39]
Hello from https://github.com/indic-dict/stardict-tibetan . 
Wondering if you could dump your dictionaries to babylon / bgl format ([eg.](https://raw.githubusercontent.com/indic-dict/stardict-tibetan/master/bo-head/84k-glossary/84k-glossary.babylon)) so that we could distribute them as stardict files for use on a variety devices (including mobile phones)?

**Comment by christiansteinert** [comment]
Hello, 

thank you for your message. Sadly I don't have the time to implement a babylon file format export. 
However, the preprocessed input files that  I am using are available in a simple CSV format at https://github.com/christiansteinert/tibetan-dictionary/tree/master/_input/dictionaries 

Maybe this is useful as a basis for creating a conversion to the babylon dictionary format by yourself. I hope that this helps somewhat.

Best wishes,
Christian
