### ISSUE TITLE
data link.

### ISSUE THREAD

**Issue by uchihatashi** [christiansteinert/tibetan-dictionary#6]
Hi, if you don't mind, where can I find the data (English-Tibetan dictionary)?
What is the format?
Can I get it in csv or any data to be saved in a tabular format?

**Comment by christiansteinert** [comment]
Hello

The data for the dictionary application is right here in the repository:
https://github.com/christiansteinert/tibetan-dictionary/tree/master/_input/dictionaries

The files are in a kind of CSV format with the term and the entry being separated by a vertical bar.

Please note, however, that the content is not owned by me and is instead owned by the respective authors.

Best wishes
Chrustuab
