### ISSUE TITLE
bod tshigs chen mo

### ISSUE THREAD

**Issue by shenzo1** [christiansteinert/tibetan-dictionary#8]
Dear Christian,

Thank you so very much for this amazing online resource that I have open every day. It is tremendously useful.

I also wanted to bring to your attention that one entry (rang rig) in the bod tshig chen mo is missing the character | and so does not show up in the results.

Thanks again for all your tremendous efforts.

Stephane

**Comment by christiansteinert** [comment]
Dear Stephane 

Thanks for letting me know. I will fix this soon and will let you know through the ticket when a corrected version is out. 
Feel free to let me know about other stuff like this and I am also open for pull requests if you know how to create one.

**Comment by christiansteinert** [comment]
The entry is fixed now in the online version of the dictionary. For the Android app this change will be rolled out with the next release when other changes have accumulated to warrant a new version of the app.
